runtime: python27
api_version: 2
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /css
  static_dir: css
- url: /js
  static_dir: js



libraries:
- name: webapp2
  version: "2.5.2"